# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile lab8/build.xml
      
  download:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        path: /home/runner/work/I-C/I-C/lab8/dist/lab8.jar

  
  javadoc:
     runs-on: ubuntu-latest
     
     steps:
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
     - name: Generate Javadoc Site
       run: ./gradlew javadocSite
     - name: Deploy Javadoc site
       run: |
        git add .
        git commit -m "Auto-generated Javadoc Site"
        git push
